CREATE TABLE eleicoes2018.candidato
(
    id int(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nome_candidato varchar(150) NOT NULL,
    nome_real varchar(150) NOT NULL,
    partido varchar(10) NOT NULL,
    cargo varchar(10) NOT NULL,
    numero varchar(5) NOT NULL,
    regiao varchar(20) NOT NULL
);
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Julien Shanahan', 'Julien Shanahan', 'PODE', 'Governador', '45', 'Santa Catarina');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Deshawn Kuhn Sr.', 'Deshawn Kuhn', 'PT', 'Governador', '18', 'Acre');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Camryn Hilpert', 'Camryn Hilpert', 'PCdoB', 'Deputado E', '8410', 'Santa Catarina');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Mr. Burley Hirthe', 'Burley Hirthe', 'PTB', 'Presidente', '54', 'Mato Grosso do Sul');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Granville White', 'Granville White', 'MDB', 'Governador', '15', 'Rio Grande do Norte');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Fidel Swift', 'Fidel Swift', 'PSDB', 'Deputado E', '5529', 'Minas Gerais');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Elias Trantow', 'Elias Trantow', 'PCB', 'Deputado E', '9787', 'Rio de Janeiro');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Prof. Maverick Gislason II', 'Maverick Gislason', 'PP', 'Deputado E', '5139', 'Tocantins');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Taylor Breitenberg I', 'Taylor Breitenberg', 'PHS', 'Senador', '941', 'Rio Grande do Sul');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Dennis Lakin', 'Dennis Lakin', 'PSC', 'Deputado F', '18819', 'Acre');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Eileen Rosenbaum', 'Eileen Rosenbaum', 'PDT', 'Governador', '16', 'Distrito Federal');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Hoyt Adams', 'Hoyt Adams', 'MDB', 'Senador', '788', 'Pernambuco');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Ned Goodwin', 'Ned Goodwin', 'PROS', 'Deputado E', '4642', 'Paraná');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Katlynn Bartell', 'Katlynn Bartell', 'PSC', 'Senador', '786', 'Bahia Bahia');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Darrin Breitenberg', 'Darrin Breitenberg', 'PEN', 'Deputado E', '7885', 'Brasil');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Waldo Macejkovic', 'Waldo Macejkovic', 'PRB', 'Presidente', '32', 'Pernambuco');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Arnulfo Daugherty', 'Arnulfo Daugherty', 'PEN', 'Deputado E', '0281', 'Acre');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Vickie Reynolds I', 'Vickie Reynolds', 'PSD', 'Deputado E', '1100', 'Paraná');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Haley Romaguera', 'Haley Romaguera', 'PT', 'Deputado E', '1709', 'Roraima');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Gustave Schmidt', 'Gustave Schmidt', 'PSOL', 'Senador', '188', 'Amapá');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Marie McKenzie DDS', 'Marie McKenzie', 'PV', 'Deputado E', '0097', 'Espírito Santo');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Brandt Grant PhD', 'Brandt Grant', 'PPS', 'Governador', '14', 'Pernambuco');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Nils Wisozk', 'Nils Wisozk', 'PSDB', 'Presidente', '74', 'Mato Grosso do Sul');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Soledad Johnson', 'Soledad Johnson', 'PCB', 'Governador', '29', 'Rio Grande do Norte');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Dandre Schimmel I', 'Dandre Schimmel', 'PP', 'Deputado E', '3603', 'Rio Grande do Norte');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Giovanna Predovic', 'Giovanna Predovic', 'PSD', 'Deputado E', '6267', 'Rio de Janeiro');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Hector Upton', 'Hector Upton', 'PHS', 'Deputado E', '7744', 'Rio Grande do Sul');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Kyra Kreiger IV', 'Kyra Kreiger', 'PSB', 'Deputado E', '2805', 'Mato Grosso do Sul');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Dr. Koby Hamill', 'Koby Hamill', 'PSTU', 'Deputado E', '6401', 'Distrito Federal');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Miss Victoria Stroman', 'Miss Victoria Stroman', 'PSL', 'Deputado E', '5928', 'Maranhão');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Mr. Alvah Kreiger', 'Alvah Kreiger', 'PEN', 'Deputado E', '4535', 'Amazonas');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Raina Koss', 'Raina Koss', 'PTC', 'Deputado E', '9962', 'Acre');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Adaline King', 'Adaline King', 'PRB', 'Senador', '435', 'Rio Grande do Sul');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Esther Goyette', 'Esther Goyette', 'PR', 'Deputado F', '68231', 'Distrito Federal');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('June Witting', 'June Witting', 'SD', 'Senador', '418', 'Mato Grosso');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Brandi Zulauf', 'Brandi Zulauf', 'PCdoB', 'Governador', '23', 'Goiás');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Meagan Franecki', 'Meagan Franecki', 'PPS', 'Deputado E', '5419', 'Distrito Federal');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Harry Fay', 'Harry Fay', 'PSL', 'Deputado E', '9187', 'Pernambuco');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Prof. Vanessa Lebsack Sr.', 'Vanessa Lebsack', 'PSDB', 'Senador', '860', 'Goiás');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Kiarra Dicki', 'Kiarra Dicki', 'PMB', 'Governador', '28', 'Distrito Federal');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Tanner Langosh', 'Tanner Langosh', 'PHS', 'Deputado E', '1347', 'Rondônia');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Prof. Eldred Cruickshank', 'Eldred Cruickshank', 'PSTU', 'Presidente', '69', 'Bahia Bahia');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Prof. Ruby Will I', 'Ruby Will', 'PP', 'Governador', '62', 'Distrito Federal');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Cassidy Hagenes', 'Cassidy Hagenes', 'PSC', 'Senador', '472', 'Rio de Janeiro');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Prof. Maxime Yundt V', 'Maxime Yundt', 'PP', 'Senador', '539', 'Paraná');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Rhett Gutkowski', 'Rhett Gutkowski', 'PP', 'Deputado E', '1758', 'Pernambuco');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Maci Bernier MD', 'Maci Bernier', 'REDE', 'Deputado F', '23658', 'Alagoas');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Kyra Johnston', 'Kyra Johnston', 'PPS', 'Deputado F', '39299', 'Minas Gerais');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Isabel Towne', 'Isabel Towne', 'PV', 'Deputado E', '8891', 'Mato Grosso do Sul');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Prof. Willy Sauer', 'Willy Sauer', 'PRP', 'Presidente', '01', 'Roraima');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Mr. Maynard Kemmer MD', 'Maynard Kemmer', 'PR', 'Deputado E', '0846', 'Espírito Santo');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Hollie Ratke', 'Hollie Ratke', 'PROS', 'Senador', '211', 'Rio de Janeiro');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Israel Cronin', 'Israel Cronin', 'PRTB', 'Presidente', '82', 'Amapá');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Kaylin Parker', 'Kaylin Parker', 'SD', 'Deputado E', '8014', 'Amazonas');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Raoul Ward', 'Raoul Ward', 'PDT', 'Deputado E', '4177', 'Maranhão');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Miss Emilia Quigley', 'Miss Emilia Quigley', 'PTB', 'Deputado E', '7152', 'Pará Pará');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Caitlyn Price DDS', 'Caitlyn Price', 'PDT', 'Senador', '127', 'Pará Pará');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Vicente Hermann', 'Vicente Hermann', 'MDB', 'Deputado E', '3618', 'Rondônia');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Ms. Shania Emmerich PhD', 'Shania Emmerich', 'PCO', 'Governador', '99', 'Paraná');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Marjory Batz', 'Marjory Batz', 'PRTB', 'Deputado F', '49419', 'Mato Grosso do Sul');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Rickey Nitzsche PhD', 'Rickey Nitzsche', 'PV', 'Presidente', '34', 'Ceará');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Ms. Destinee Ward', 'Destinee Ward', 'PTC', 'Senador', '570', 'Santa Catarina');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Tate Cronin', 'Tate Cronin', 'PPL', 'Governador', '75', 'Paraná');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Aaliyah Crona', 'Aaliyah Crona', 'REDE', 'Senador', '918', 'Roraima');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Ross Considine', 'Ross Considine', 'PPS', 'Deputado F', '40118', 'Tocantins');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Tyrese Gibson', 'Tyrese Gibson', 'PCdoB', 'Deputado F', '58673', 'Piauí');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Garland Lindgren', 'Garland Lindgren', 'PPS', 'Senador', '345', 'Rondônia');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Miss Fannie Kuphal', 'Miss Fannie Kuphal', 'PTC', 'Deputado E', '3948', 'Amazonas');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Dr. Rogers Medhurst', 'Rogers Medhurst', 'PSDB', 'Governador', '71', 'Maranhão');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Mrs. Trycia Koepp II', 'Trycia Koepp', 'PSB', 'Senador', '294', 'Amapá');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Horacio Donnelly', 'Horacio Donnelly', 'PSDC', 'Presidente', '29', 'Santa Catarina');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Bette Moen', 'Bette Moen', 'PPS', 'Deputado E', '8748', 'Acre');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Jerald VonRueden', 'Jerald VonRueden', 'PRTB', 'Senador', '543', 'Paraíba');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Rigoberto Bins', 'Rigoberto Bins', 'PSB', 'Deputado E', '1995', 'Santa Catarina');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Linda Carter', 'Linda Carter', 'PPS', 'Deputado E', '8247', 'Rio de Janeiro');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Idella Eichmann MD', 'Idella Eichmann', 'PRB', 'Deputado E', '7288', 'Paraíba');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Braeden Casper', 'Braeden Casper', 'PROS', 'Deputado E', '5860', 'Acre');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Savanah Heathcote', 'Savanah Heathcote', 'PSD', 'Deputado E', '0896', 'Rio de Janeiro');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Delilah Bosco', 'Delilah Bosco', 'NOVO', 'Deputado F', '63292', 'Piauí');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Federico Murazik', 'Federico Murazik', 'PSB', 'Governador', '32', 'Amapá');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Marianna Legros IV', 'Marianna Legros', 'PDT', 'Deputado F', '32544', 'Ceará');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Prof. Anna Stracke', 'Anna Stracke', 'MDB', 'Senador', '525', 'Alagoas');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Lennie Dach', 'Lennie Dach', 'PR', 'Senador', '631', 'São Paulo');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Chaya Smitham', 'Chaya Smitham', 'PROS', 'Deputado E', '5269', 'Sergipe');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Korey Langworth', 'Korey Langworth', 'PSTU', 'Governador', '74', 'Espírito Santo');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Prof. Clovis McDermott DVM', 'Clovis McDermott', 'PEN', 'Deputado E', '7126', 'Paraná');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Maxwell Smitham', 'Maxwell Smitham', 'PPS', 'Deputado E', '6687', 'Brasil');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Mrs. Kavon Runolfsson', 'Kavon Runolfsson', 'PEN', 'Deputado F', '08964', 'Mato Grosso do Sul');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Ms. Krystel Roberts MD', 'Krystel Roberts', 'PRTB', 'Deputado E', '3618', 'Ceará');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Houston Ryan', 'Houston Ryan', 'PCO', 'Presidente', '75', 'São Paulo');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Prof. Maude Steuber PhD', 'Maude Steuber', 'PTB', 'Governador', '51', 'Acre');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Mr. Johnny Donnelly II', 'Johnny Donnelly', 'SD', 'Governador', '32', 'Rio de Janeiro');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Prof. Grover Abbott', 'Grover Abbott', 'PPS', 'Deputado F', '24391', 'Pernambuco');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Prof. Elaina Will III', 'Elaina Will', 'MDB', 'Deputado F', '51280', 'São Paulo');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Prof. Eddie Bauch Jr.', 'Eddie Bauch', 'PEN', 'Governador', '05', 'São Paulo');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Holly Oberbrunner', 'Holly Oberbrunner', 'PODE', 'Deputado E', '3318', 'Maranhão');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Jacklyn Weber', 'Jacklyn Weber', 'PSC', 'Deputado E', '7382', 'Bahia Bahia');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Prof. Lilyan Veum PhD', 'Lilyan Veum', 'PEN', 'Presidente', '63', 'Rondônia');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Craig Zboncak', 'Craig Zboncak', 'PDT', 'Deputado E', '2648', 'Rondônia');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Yolanda Fadel IV', 'Yolanda Fadel', 'PCO', 'Deputado F', '92604', 'Rio Grande do Sul');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Rosemary Quigley', 'Rosemary Quigley', 'PSB', 'Presidente', '34', 'Pará Pará');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Lydia Dooley', 'Lydia Dooley', 'SD', 'Deputado E', '0615', 'Rondônia');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Archibald Robel', 'Archibald Robel', 'PSL', 'Deputado E', '4048', 'Pernambuco');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Dr. Cruz Treutel PhD', 'Cruz Treutel', 'PRP', 'Senador', '276', 'Acre');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Jerel Mayer II', 'Jerel Mayer', 'NOVO', 'Deputado F', '97553', 'Goiás');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Regan Jenkins Sr.', 'Regan Jenkins', 'DEM', 'Deputado F', '53172', 'São Paulo');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Cheyenne Barton', 'Cheyenne Barton', 'PODE', 'Senador', '151', 'Amazonas');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Prof. Winston Upton', 'Winston Upton', 'PT', 'Deputado E', '4984', 'Goiás');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Cloyd Friesen', 'Cloyd Friesen', 'PR', 'Deputado E', '6132', 'Pernambuco');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Serena Feeney', 'Serena Feeney', 'PCB', 'Senador', '631', 'Distrito Federal');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Gordon Mosciski', 'Gordon Mosciski', 'DEM', 'Governador', '82', 'Ceará');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Heidi Nitzsche', 'Heidi Nitzsche', 'PR', 'Deputado E', '9646', 'Mato Grosso do Sul');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Mrs. Bernadette Gorczany I', 'Bernadette Gorczany', 'PR', 'Presidente', '08', 'Rio de Janeiro');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Mr. Chester Bailey DDS', 'Chester Bailey', 'PMB', 'Senador', '423', 'Mato Grosso do Sul');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Travon Friesen', 'Travon Friesen', 'PCB', 'Senador', '548', 'Brasil');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Mr. Micheal Pfannerstill', 'Micheal Pfannerstill', 'PSB', 'Deputado E', '2325', 'Sergipe');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Nicholas Runolfsson', 'Nicholas Runolfsson', 'PCdoB', 'Senador', '584', 'Rio Grande do Sul');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Howell Veum', 'Howell Veum', 'PT', 'Deputado E', '4873', 'Paraná');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Prof. Kevin Wyman', 'Kevin Wyman', 'PHS', 'Governador', '92', 'Rondônia');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Myrtice Hirthe', 'Myrtice Hirthe', 'PSDB', 'Deputado E', '5581', 'Ceará');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Hank Walker', 'Hank Walker', 'REDE', 'Governador', '37', 'Minas Gerais');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Imelda Toy', 'Imelda Toy', 'PCdoB', 'Deputado E', '0296', 'Piauí');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Haley Bernhard', 'Haley Bernhard', 'PCO', 'Senador', '207', 'Rondônia');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Mr. Jasmin Parker', 'Jasmin Parker', 'PCB', 'Deputado E', '0384', 'Espírito Santo');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Gene Simonis MD', 'Gene Simonis', 'REDE', 'Deputado E', '3548', 'Rio Grande do Norte');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Vernon Moen Jr.', 'Vernon Moen', 'REDE', 'Senador', '477', 'Brasil');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Jadyn Toy', 'Jadyn Toy', 'PSB', 'Senador', '731', 'Acre');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Green Douglas', 'Green Douglas', 'PT', 'Deputado E', '1481', 'Amazonas');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Eldridge Murazik', 'Eldridge Murazik', 'PR', 'Senador', '614', 'Brasil');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Garth Rau', 'Garth Rau', 'PTB', 'Deputado E', '3655', 'Sergipe');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Dr. Travon Hilpert III', 'Travon Hilpert', 'PCO', 'Deputado E', '0514', 'Mato Grosso do Sul');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Theron Klocko', 'Theron Klocko', 'PMB', 'Presidente', '07', 'Mato Grosso do Sul');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Dudley Jacobson', 'Dudley Jacobson', 'PEN', 'Senador', '616', 'Minas Gerais');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Remington Douglas DDS', 'Remington Douglas', 'PTC', 'Deputado E', '9391', 'Ceará');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Amber Jaskolski III', 'Amber Jaskolski', 'PRTB', 'Governador', '27', 'Bahia Bahia');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Valentine Macejkovic', 'Valentine Macejkovic', 'PPL', 'Deputado E', '3280', 'Piauí');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Laila Rodriguez', 'Laila Rodriguez', 'REDE', 'Deputado E', '9706', 'Mato Grosso do Sul');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Dr. Augustus Pagac', 'Augustus Pagac', 'PDT', 'Deputado E', '4988', 'Amazonas');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Michele Rolfson Jr.', 'Michele Rolfson', 'NOVO', 'Senador', '098', 'Roraima');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Mr. Odell Kuvalis', 'Odell Kuvalis', 'PSDC', 'Governador', '12', 'Rio de Janeiro');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Dr. Jackie Casper Jr.', 'Jackie Casper', 'MDB', 'Deputado F', '97856', 'Alagoas');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Ashlee Predovic DDS', 'Ashlee Predovic', 'PSL', 'Governador', '81', 'Paraná');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Mr. Seamus Monahan', 'Seamus Monahan', 'PSB', 'Deputado F', '19025', 'Santa Catarina');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Ronaldo Ward', 'Ronaldo Ward', 'PTB', 'Deputado E', '2879', 'Rio Grande do Norte');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Elizabeth VonRueden', 'Elizabeth VonRueden', 'SD', 'Deputado E', '7048', 'Sergipe');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Martine Maggio', 'Martine Maggio', 'PMB', 'Deputado F', '76106', 'Paraíba');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Mr. Diamond Sawayn V', 'Diamond Sawayn', 'PSTU', 'Senador', '901', 'Paraná');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Mr. Scot Beatty', 'Scot Beatty', 'PCdoB', 'Senador', '865', 'Pará Pará');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Celestino Baumbach', 'Celestino Baumbach', 'PPL', 'Deputado E', '4443', 'Mato Grosso do Sul');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Kiara Donnelly', 'Kiara Donnelly', 'PSL', 'Senador', '762', 'Rondônia');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Ms. Violet Paucek', 'Violet Paucek', 'NOVO', 'Presidente', '68', 'Paraná');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Bridie Kunde', 'Bridie Kunde', 'PSD', 'Senador', '135', 'Distrito Federal');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Casandra Hettinger', 'Casandra Hettinger', 'PT', 'Presidente', '96', 'Bahia Bahia');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Claudine Jaskolski', 'Claudine Jaskolski', 'PSDC', 'Deputado E', '6483', 'Paraná');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Beulah Douglas', 'Beulah Douglas', 'NOVO', 'Deputado E', '3989', 'Rio Grande do Sul');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Jaime Powlowski', 'Jaime Powlowski', 'PSTU', 'Senador', '932', 'Distrito Federal');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Mr. Cicero Schaefer', 'Cicero Schaefer', 'PODE', 'Deputado E', '7996', 'Santa Catarina');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Destany Hegmann', 'Destany Hegmann', 'PMN', 'Governador', '79', 'Roraima');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Onie Macejkovic', 'Onie Macejkovic', 'PRB', 'Governador', '04', 'Amapá');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Sanford Reilly', 'Sanford Reilly', 'PSTU', 'Deputado F', '29329', 'Santa Catarina');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Efrain Friesen', 'Efrain Friesen', 'PTC', 'Deputado E', '3572', 'Minas Gerais');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Felipa Bauch Jr.', 'Felipa Bauch', 'MDB', 'Deputado E', '5107', 'Piauí');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Joanne Swaniawski', 'Joanne Swaniawski', 'PROS', 'Deputado E', '0438', 'Pará Pará');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Arthur Lakin', 'Arthur Lakin', 'PRTB', 'Deputado E', '3038', 'Brasil');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Ari Mills', 'Ari Mills', 'PSOL', 'Presidente', '83', 'Paraná');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Prof. Torey Carroll DDS', 'Torey Carroll', 'NOVO', 'Senador', '407', 'Minas Gerais');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Liliana Lebsack Jr.', 'Liliana Lebsack', 'PCO', 'Senador', '159', 'Alagoas');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Autumn Grady DVM', 'Autumn Grady', 'PT', 'Senador', '985', 'Minas Gerais');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Dylan Tillman', 'Dylan Tillman', 'PR', 'Deputado E', '5295', 'Sergipe');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Larissa Bernhard', 'Larissa Bernhard', 'PTC', 'Presidente', '05', 'Paraná');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Dr. Icie Watsica II', 'Icie Watsica', 'PSD', 'Deputado E', '3734', 'Tocantins');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Dr. Adrien Reinger Sr.', 'Adrien Reinger', 'PT', 'Senador', '204', 'Rio de Janeiro');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Ms. Princess Becker DVM', 'Princess Becker', 'PMB', 'Senador', '672', 'Bahia Bahia');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Dannie Boyle', 'Dannie Boyle', 'PRB', 'Deputado E', '9871', 'Paraíba');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Dr. Green Ankunding DVM', 'Green Ankunding', 'PSL', 'Deputado E', '4564', 'Amapá');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Chelsie Lynch', 'Chelsie Lynch', 'PODE', 'Deputado E', '5155', 'Pará Pará');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Ernie Gleason', 'Ernie Gleason', 'PTC', 'Senador', '197', 'Piauí');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Mr. Elliott Rice', 'Elliott Rice', 'PRTB', 'Senador', '698', 'Mato Grosso do Sul');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Fidel Yundt', 'Fidel Yundt', 'PROS', 'Presidente', '73', 'Amapá');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Sister Mante', 'Sister Mante', 'PRP', 'Governador', '54', 'Goiás');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Ocie Feest', 'Ocie Feest', 'PPS', 'Presidente', '47', 'Alagoas');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Amina Effertz', 'Amina Effertz', 'PR', 'Governador', '75', 'Amapá');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Jacinthe Boyle PhD', 'Jacinthe Boyle', 'PSC', 'Deputado E', '8547', 'Paraíba');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Michele Pfannerstill', 'Michele Pfannerstill', 'PSDC', 'Senador', '264', 'São Paulo');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Ayana Konopelski', 'Ayana Konopelski', 'PSDC', 'Senador', '720', 'Tocantins');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Miss Reta Feil MD', 'Miss Reta Feil', 'DEM', 'Senador', '953', 'Minas Gerais');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Jan Harber', 'Jan Harber', 'PROS', 'Deputado F', '10487', 'Rondônia');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Miss Rosamond Smith', 'Miss Rosamond Smith', 'DEM', 'Senador', '533', 'Piauí');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Mafalda Rutherford', 'Mafalda Rutherford', 'PTC', 'Governador', '35', 'Mato Grosso do Sul');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Vivienne Abshire', 'Vivienne Abshire', 'PODE', 'Presidente', '49', 'Rondônia');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Hayley Ryan', 'Hayley Ryan', 'DEM', 'Presidente', '41', 'Amazonas');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Mr. Nicola Grady', 'Nicola Grady', 'PHS', 'Senador', '973', 'Tocantins');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Ron Satterfield', 'Ron Satterfield', 'PROS', 'Governador', '56', 'Sergipe');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Caterina Morar', 'Caterina Morar', 'REDE', 'Deputado F', '17684', 'Ceará');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Claudie Wilderman', 'Claudie Wilderman', 'PSL', 'Presidente', '59', 'Goiás');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Rose Murazik', 'Rose Murazik', 'NOVO', 'Governador', '28', 'Santa Catarina');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Miss Cierra Gorczany PhD', 'Miss Cierra Gorczany', 'PDT', 'Senador', '829', 'Pará Pará');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Mauricio Parisian', 'Mauricio Parisian', 'PPL', 'Presidente', '61', 'Rondônia');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Ollie Gislason Jr.', 'Ollie Gislason', 'PSDB', 'Deputado E', '8260', 'Acre');
INSERT INTO eleicoes2018.candidato (nome_candidato, nome_real, partido, cargo, numero, regiao) VALUES ('Prof. Ena Stark I', 'Ena Stark', 'PPS', 'Senador', '805', 'Pernambuco');